version: 2.1
orbs:
  node: circleci/node@5.1.0 # Use the CircleCI Node Orb
  cypress: cypress-io/cypress@3
jobs:
  unit_test: # Define a new job for Jest tests, renamed to avoid confusion
    executor: node/default
    steps:
      - checkout
      - node/install-packages: # Cache and restore npm dependencies
          pkg-manager: npm
      - run: CI=true npm run test # Make sure the tests only run once
      - store_test_results: # Store the test results for CircleCI to read
          path: test-results.xml # Modify this with your actual test results path
workflows:
  build: # Renamed the workflow from "test" to "build" to avoid confusion
    jobs:
      - unit_test # Run your Jest test job
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          start-command: "npm run start"
