version: 2.1
orbs:
  node: circleci/node@5.1.0 # Use the CircleCI Node Orb
  cypress: cypress-io/cypress@3
  mailer-orb: sudiptog81/mailer-orb@1.0.0
jobs:
  unit_test: # Define a new job for Jest tests, renamed to avoid confusion
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies for test-genie
          command: npm install
          working_directory: test-genie
      - run:
          name: Install dependencies for test-genie-backend
          command: npm install
          working_directory: test-genie/test-genie-backend
      - run: CI=true npm run test # Make sure the tests only run once
      - store_test_results: # Store the test results for CircleCI to read
          path: test-results.xml # Modify this with your actual test results path
workflows:
  build: # Renamed the workflow from "test" to "build" to avoid confusion
    jobs:
      - mailer-orb/mail:
            body: Success! 
            from: dcblanton78@gmail.com 
            subject: Success 
            to: dcblanton78@gmail.com 
      - unit_test # Run your Jest test job
      - cypress/run:
          cypress-command: npx cypress run --browser electron --headless --record
          start-command: "npm run start"
          
